language: ruby
rvm:
  - 2.6.1
gemfile:
  - Gemfile

env:
  global:
    CC_TEST_REPORTER_ID=971fdfa37b0f4cb293873ded00cd637a40a6ceb696573e0a565f3d71f38e8538

before_install:
  - gem install rails
  - gem update --system
  - gem install bundler
  - bundle install
  - psql -c 'create database orapma_development;' -U postgres
  - psql -c 'create database orapma_test;' -U postgres
  - psql -c 'CREATE USER railsuser SUPERUSER INHERIT CREATEDB CREATEROLE' -U postgres
  - psql -c "alter user railsuser with password 'Rails@123'" -U postgres

install:
  - bundle install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - rails db:migrate
  - bundle exec rake

services:
  - postgresql

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT